project:
  type: website

website:
  title: "James Thompson"
  description: "Personal website of James Thompson, mainly to post my ideas and thoughts as well as give myself a online space for identification."
  site-url: "https://james.sjhl.nz"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        href: posts.qmd
      - text: "Short Forms"
        href: shorts.qmd
      - about-me.qmd
      - icon: github
        href: https://github.com/1jamesthompson1
      - icon: instagram
        href: https://instagram.com/1jamesthompson1
      - icon: linkedin
        href: https://www.linkedin.com/in/james-thompson-532246208/

  repo-url: "https://github.com/1jamesthompson1/1jamesthompson1.github.io"
  issue-url: "https://github.com/1jamesthompson1/1jamesthompson1.github.io/issues"
  page-navigation: true

  page-footer:
    center:
      - text: "About Me"
        href: about-me.qmd
      - text: "CC BY-SA 4.0"
        href: https://creativecommons.org/licenses/by-sa/4.0/
      - text: "Contact Me: 1jamesthompson1@gmail"
        href: "mailto:1jamesthompson1@gmail.com"
comments:
  giscus: 
    repo: 1jamesthompson1/1jamesthompson1.github.io
    mapping: pathname
    category: Announcements
    

format:
  html:
    theme: yeti
    css: styles.css
    include-in-header:
        - text: |
            <script data-goatcounter="https://1jamesthompson1.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>'
